### act action file (emulates Github Actions) ###

jobs:
  runTestLocal:
    container: drschwabe/coinos-tests:v0.0.4
    name: Headless Puppeteer Integration Test (Local)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : coinos-tests
      run : cd /coinos-tests; npm run test-headless