on: [ push, pull_request ]
name: Coinos
jobs:
  installAndTest:
    name: Install Coinos and run integration test
#    container : drschwabe/coinos-tests:latest
    runs-on: ubuntu-latest
    steps: #required for act: 
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        
    - run: npm install -g yarn

    # - uses: actions/checkout@v2
    #   #name : checkout coinos-ui
    #   with:
    #     repository: coinos/coinos-ui
    #     path: coinos-ui

    - uses: actions/checkout@v2
      name: checkout coinos-server
      with:
        repository: coinos/coinos-server
        path: coinos-server

    - name: Install sudo (act only)
      run: apt update && apt install sudo
      if: env.ACT=='true'

    - run: |
        curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      name: install docker-compose (act only)
      if: env.ACT=='true'

    - run: |
        sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
      name: sudo install docker-compose 
      if: env.ACT!='true'      

    - run : | 
        #yarn
        cd coinos-server 
        cp -rf sampleconfig "./config" 
        cp .env.sample ".env" 
        cp fx.sample "fx" 
        mkdir "mysql" 
        cp db/schema.sql "mysql/"
      name : install and setup coinos-server

    - run : |
        cd coinos-server
        docker-compose up -d --force-recreate --remove-orphans maria
        sleep 10
        docker exec -i mariadb mysql --host 127.0.0.1 --port 3306 --protocol=tcp -ppassword < mysql/schema.sql
      name: setup maria schema 

    - run: |
        cd coinos-server
        docker-compose down
        docker-compose up -d
      name: docker-compose down and up 

    - uses: actions/checkout@v2
      name: checkout coinos-tests
      with:
        path: coinos-tests

    # - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    #   name: Login to DockerHub

    #- run: cd coinos-tests && docker-compose build 
      #name: Build test docker image 

   # - run : cd coinos-tests && docker-compose up --force-recreate
    #- run : cd coinos-tests
    - run : docker-compose up
      working-directory: coinos-tests

    #- run : ls 
    #- run :  docker-compose up
    #- run : cd coinos-tests && docker-compose run coinos-tests "npm run test-headless"
    #- run: cd coinos-tests && docker-compose run coinos-tests
      #name : Test

    
    # - uses: addnab/docker-run-action@v3
    #   name : test-headless
    # - with : 
    #     image: drschwabe/coinos-tests:latest
    #     shell: bash 

        # run : |
        #   cd "coinos-tests"
        #   npm run test-headless
    # - name: coinos-tests docker 
    # - uses: docker://drschwabe/coinos-tests:latest
    # - with: 
    #     run : cd coinos-tests && npm run test-headless
    #   env : 
    #     BASE_URL : http://ui:8085        

    # - run : cd coinos-tests && npm run test-headless
    #   name : perform coinos-tests
    #   env : 
    #     BASE_URL : http://ui:8085