on: [ push, pull_request ]
name: Coinos
jobs:
  runTests:
    container : drschwabe/coinos-tests:latest
    name: Headless Puppeteer Integration Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name : coinos-tests
      run : npm run test-headless
      env : 
        BASE_URL : http://localhost:8085/

