on: [ push, pull_request ]
name: Coinos
jobs:
  installAndTest:
    name: Install Coinos and perform integration test
    runs-on: ubuntu-latest
    steps:
    - run: npm install -g yarn

    # - uses: actions/checkout@v2
    #   #name : checkout coinos-ui
    #   with:
    #     repository: coinos/coinos-ui
    #     path: coinos-ui

    - uses: actions/checkout@v2
      name: checkout coinos-server
      with:
        repository: coinos/coinos-server
        path: coinos-server

    - run: sudo curl -L https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - run: sudo chmod +x /usr/local/bin/docker-compose

    - run : | 
        #yarn \
        ls \
        && echo '------------------------------------------' \
        && cd coinos-server \
        && ls \
        && cp -rf sampleconfig "./config" \
        && cp .env.sample ".env" \
        && cp fx.sample "fx" \
        && mkdir "mysql" \
        && ls \
        && cp db/schema.sql "mysql/"
      name : install and setup coinos-server
    - run : |
        #docker-compose rm -v \
        cd coinos-server \
        && docker-compose up -d --force-recreate --remove-orphans maria \
        && sleep 10 \
        && docker exec -i mariadb mysql --host 127.0.0.1 --port 3306 --protocol=tcp -ppassword < mysql/schema.sql
      name: setup maria schema 

    - run: |
        cd coinos-server \
        &&  docker-compose down \
        &&  docker-compose up -d
      name: docker-compose down and up 
    
#    - uses: actions/checkout@v2
    - uses: docker://drschwabe/coinos-tests:latest

    - run : cd coinos-tests && npm run test-headless
      name : perform coinos-tests
      env : 
        BASE_URL : http://ui:8085